version: "3.7"
services:

  traefik:
    hostname: traefik
    image: traefik:v1.7.16
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}

    networks:
      - default
      - traefik_proxy

    ports:
      - "80:80"
      - "443:443"

    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/traefik:/etc/traefik
      - ${USERDIR}/docker/shared:/shared


  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    container_name: traefik-forward-auth
    restart: always

    networks:
      - traefik_proxy

    environment:
      - CLIENT_ID=${TRAEFIK_CLIENT_ID}
      - CLIENT_SECRET=${TRAEFIK_CLIENT_SECRET}
      - OIDC_ISSUER=https://accounts.google.com
      - SECRET=${TRAEFIK_SECRET}
      - COOKIE_DOMAINS=${DOMAINNAME}
      - AUTH_HOST=auth.${DOMAINNAME}
      - WHITELIST=${TRAEFIK_WHITELIST}

    labels:
      # TRAEFIK ENABLE
      - traefik.enable=true
      - traefik.frontend.rule=Host:auth.${DOMAINNAME}
      - traefik.port=4181

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  apache:
    image: httpd
    container_name: apache-startpage
    restart: always

    volumes:
      - ${USERDIR}/docker/apache-startpage/data:/usr/local/apache2/htdocs/

    networks:
      - traefik_proxy

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${DOMAINNAME}"
      - "traefik.port=80"

      # SPECIAL CATCH ALL
      - "traefik.frontend.rule=HostRegexp:{catchall:.*}"
      - "traefik.frontend.priority=1"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data

    networks:
      - traefik_proxy

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:portainer.${DOMAINNAME}"
      - "traefik.port=9000"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  watchtower:
    container_name: watchtower
    restart: always
    image: v2tec/watchtower
    command: --schedule "0 0 4 * * *" --cleanup

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: always

    volumes:
      - ${USERDIR}/docker/tautulli/config:/config

    networks:
      - traefik_proxy

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:tautulli.${DOMAINNAME}"
      - "traefik.port=8181"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  deluge:
    image: linuxserver/deluge
    container_name: deluge
    restart: always

    volumes:
      - ${USERDIR}/docker/deluge/config:/config
      - ${DELUGE_TORRENTS_DIR}:/torrents
      - ${DELUGE_DOWNLOADS_DIR}:/downloads

    networks:
      - traefik_proxy

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:deluge.${DOMAINNAME}"
      - "traefik.port=8112"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  db:
    image: mariadb
    container_name: db
    restart: always

    networks:
      - traefik_proxy

    volumes:
      - ${USERDIR}/docker/db:/var/lib/mysql


  adminer:
    image: adminer
    container_name: adminer
    restart: always

    depends_on:
      - db

    networks:
      - traefik_proxy

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:adminer.${DOMAINNAME}"
      - "traefik.port=8080"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  guacd:
    image: "guacamole/guacd"
    container_name: guacd
    hostname: guacd
    restart: always

    networks:
      - traefik_proxy

    volumes:
      - "${USERDIR}/docker/guacd/data:/data"
      - "${USERDIR}/docker/guacd/conf:/conf:ro"


  guacamole:
    image: "guacamole/guacamole"
    container_name: guacamole
    hostname: guacamole
    restart: always

    networks:
      - traefik_proxy

    volumes:
      - "${USERDIR}/docker/guacamole/data:/data"
      - "${USERDIR}/docker/guacamole/conf:/conf:ro"

    environment:
      - "GUACD_HOSTNAME=guacd"
      - "GUACD_PORT=4822"
      - "MYSQL_HOSTNAME=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=guacamole"
      - "MYSQL_USER=guac"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "GUACAMOLE_HOME=/data"

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:guacamole.${DOMAINNAME};AddPrefix: /guacamole;"
      - "traefik.port=8080"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  backuppc:
    container_name: backuppc
    image: adferrand/backuppc
    restart: always

    volumes:
      - '${USERDIR}/docker/backuppc/etc:/etc/backuppc'
      - '${USERDIR}/docker/backuppc/home:/home/backuppc'
      - '${USERDIR}/docker/backuppc/data:/data/backuppc'

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:backup.${DOMAINNAME};"
      - "traefik.port=8080"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"



# --- END OF SERVICES --- #

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

# --- END OF NETWORKS --- #
