version: "3.7"
services:

## --- SPECIAL SEPARATE docker-compose TO PROTECT AGAINST ---
## --- FAILED CONTAINERS TAKING DOWN VITAL SERVICES ---

# --- NETWORK SERVICES --- #
  traefik:
    hostname: traefik
    image: traefik:v1.7.16
    container_name: traefik
    restart: always
    domainname: ${DOMAINNAME}

    networks:
      - default
      - traefik_proxy

    ports:
      - "80:80"
      - "443:443"

    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      - CF_API_KEY=${CLOUDFLARE_API_KEY}

    environment:
      - PUID=${PUID}
      - PGID=${PGID}

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:traefik.${DOMAINNAME}"
      - "traefik.port=8080"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/docker/storage/traefik:/etc/traefik


  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    container_name: traefik-forward-auth
    restart: always

    networks:
      - traefik_proxy

    environment:
      - CLIENT_ID=${TRAEFIK_CLIENT_ID}
      - CLIENT_SECRET=${TRAEFIK_CLIENT_SECRET}
      - OIDC_ISSUER=https://accounts.google.com
      - SECRET=${TRAEFIK_SECRET}
      - COOKIE_DOMAINS=${DOMAINNAME}
      - AUTH_HOST=auth.${DOMAINNAME}
      - WHITELIST=${TRAEFIK_WHITELIST}

    environment:
      - PUID=${PUID}
      - PGID=${PGID}

    labels:
      # TRAEFIK ENABLE
      - traefik.enable=true
      - traefik.frontend.rule=Host:auth.${DOMAINNAME}
      - traefik.port=4181

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


# --- OTHER TOOLS --- #
  guacd:
    image: "guacamole/guacd"
    container_name: guacd
    hostname: guacd
    restart: always

    networks:
      - traefik_proxy

    volumes:
      - "${USERDIR}/docker/storage/guacd/data:/data"
      - "${USERDIR}/docker/storage/guacd/conf:/conf:ro"

    environment:
      - PUID=${PUID}
      - PGID=${PGID}


  guacamole:
    image: "guacamole/guacamole"
    container_name: guacamole
    hostname: guacamole
    restart: always

    networks:
      - traefik_proxy

    volumes:
      - "${USERDIR}/docker/storage/guacamole/data:/data"
      - "${USERDIR}/docker/storage/guacamole/conf:/conf:ro"

    environment:
      - PUID=${PUID}
      - PGID=${PGID}

    environment:
      - "GUACD_HOSTNAME=guacd"
      - "GUACD_PORT=4822"
      - "MYSQL_HOSTNAME=db"
      - "MYSQL_PORT=3306"
      - "MYSQL_DATABASE=guacamole"
      - "MYSQL_USER=guac"
      - "MYSQL_PASSWORD=${GUACDB_PASSWORD}"
      - "GUACAMOLE_HOME=/data"

    labels:
      # TRAEFIK ENABLE
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:guacamole.${DOMAINNAME};AddPrefix: /guacamole;"
      - "traefik.port=8080"

      # AUTH BLOCK
      - "traefik.frontend.auth.forward.address=http://traefik-forward-auth:4181"
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Forwarded-User"
      - "traefik.frontend.auth.forward.trustForwardHeader=true"

      # GENERAL SECURITY
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


  db:
    image: mariadb
    container_name: db
    restart: always

    networks:
      - traefik_proxy

    volumes:
      - ${USERDIR}/docker/storage/db:/var/lib/mysql

    environment:
      - PUID=${PUID}
      - PGID=${PGID}

# --- END OF SERVICES --- #

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

# --- END OF NETWORKS --- #
